In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/robi-datathon-30-qualifier-problem-3/boxes.csv
/kaggle/input/robi-datathon-30-qualifier-problem-3/purchase.csv
/kaggle/input/robi-datathon-30-qualifier-problem-3/problem 3.csv
/kaggle/input/robi-datathon-30-qualifier-problem-3/sample submission 3.csv

# Load Datasets

In [2]:
boxes_df = pd.read_csv('/kaggle/input/robi-datathon-30-qualifier-problem-3/boxes.csv')
problem_3_df = pd.read_csv('/kaggle/input/robi-datathon-30-qualifier-problem-3/problem 3.csv')
purchase_df = pd.read_csv('/kaggle/input/robi-datathon-30-qualifier-problem-3/purchase.csv')

sample_submission_3 = pd.read_csv('/kaggle/input/robi-datathon-30-qualifier-problem-3/sample submission 3.csv')

In [3]:
boxes_df

     BOX_ID   QUALITY                  DELIVERY_OPTION  MILK  MEAT  UNIT_PRICE
0         1   Premium              Home Delivery - CoD   0.0   2.7        9.96
1         2   Premium              Home Delivery - CoD   0.0   2.3       11.96
2         3   Premium              Home Delivery - CoD   0.0   2.4       11.96
3         4   Premium              Home Delivery - CoD   0.0   2.5       11.96
4         5   Premium              Home Delivery - CoD   0.0   2.6       11.96
..      ...       ...                              ...   ...   ...         ...
285     286  Standard  Home Delivery - Digital Payment   0.0   4.0       15.96
286     287  Standard  Home Delivery - Digital Payment   0.0   2.9       15.96
287     288  Standard  Home Delivery - Digital Payment   0.0   3.6       15.96
288     289  Standard  Home Delivery - Digital Payment   0.0   4.7       15.96
289     290  Standard  Home Delivery - Digital Payment  12.0   1.8       19.98

[290 rows x 6 columns]

In [4]:
boxes_df.isnull().sum().sum()

0

In [5]:
problem_3_df

        MAGIC_KEY
0     2BCFE9C06A7
1     2C2A872B5A2
2     2C6A897671B
3     2C6F1287F53
4     2C658198CC9
...           ...
5374  2C0804EFE49
5375  2C080B48630
5376  2C08243C58E
5377  2C082C78575
5378  2C083B1F3E5

[5379 rows x 1 columns]

In [6]:
problem_3_df.isnull().sum().sum()

0

In [7]:
purchase_df

        PURCHASE_DATE    MAGIC_KEY  BOX_ID  BOX_COUNT
0            1/2/2019  2CED678A247    12.0        1.0
1            1/2/2019  2BF58D91BA1    12.0        1.0
2            1/2/2019  2C15B86534E    99.0        1.0
3            1/2/2019  2C32D9A859A     6.0        1.0
4            1/2/2019  2C7A55404D1     4.0        1.0
...               ...          ...     ...        ...
2455859    28/10/2018  2BD992B5538    12.0        1.0
2455860    28/10/2018  2C97CD72233    17.0        1.0
2455861    28/10/2018  2C91C61D372    40.0        1.0
2455862    28/10/2018  2CD70CFC4E3    51.0        1.0
2455863    28/10/2018  2C4792A5B84     4.0        1.0

[2455864 rows x 4 columns]

In [8]:
purchase_df.isnull().sum().sum()

94

In [9]:
sample_submission_3

        MAGIC_KEY  MEAT
0     2BCFE9C06A7  25.2
1     2C2A872B5A2  25.2
2     2C6A897671B  25.2
3     2C6F1287F53  25.2
4     2C658198CC9  25.2
...           ...   ...
5374  2C0804EFE49  25.2
5375  2C080B48630  25.2
5376  2C08243C58E  25.2
5377  2C082C78575  25.2
5378  2C083B1F3E5  25.2

[5379 rows x 2 columns]

In [10]:
sample_submission_3.isnull().sum().sum()

0

In [11]:
merged_df = pd.merge(boxes_df, purchase_df, on='BOX_ID', how='outer')
merged_df

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,PURCHASE_DATE,MAGIC_KEY,BOX_COUNT
0,1.0,Premium,Home Delivery - CoD,0.0,2.7,9.96,4/2/2019,2C88D36D1FC,1.0
1,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2BF011BDB38,1.0
2,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2CA0EE8F2B3,1.0
3,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2C623730B09,1.0
4,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2CA6CE1054F,1.0
...,...,...,...,...,...,...,...,...,...
2455859,NaN,NaN,NaN,NaN,NaN,NaN,9/10/2018,2BE34886311,NaN
2455860,NaN,NaN,NaN,NaN,NaN,NaN,18/10/2018,2BE266F8C55,NaN
2455861,NaN,NaN,NaN,NaN,NaN,NaN,18/10/2018,2BDC3619EAF,NaN
2455862,NaN,NaN,NaN,NaN,NaN,NaN,17/10/2018,2BF1D98D0B2,NaN
2455863,NaN,NaN,NaN,NaN,NaN,NaN,16/10/2018,2C2C8844F09,NaN

In [12]:
merged_df.isnull().sum()

BOX_ID             47
QUALITY            64
DELIVERY_OPTION    64
MILK               64
MEAT               64
UNIT_PRICE         64
PURCHASE_DATE       0
MAGIC_KEY           0
BOX_COUNT          47
dtype: int64

# Filling NaN values with the median of each column

In [13]:
for column in merged_df.columns:
    mode_value = merged_df[column].mode()[0]  # mode() returns a Series, [0] gets the mode value
    merged_df[column].fillna(mode_value, inplace=True)

/tmp/ipykernel_24/1702747092.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df[column].fillna(mode_value, inplace=True)

In [14]:
merged_df.isnull().sum()

BOX_ID             0
QUALITY            0
DELIVERY_OPTION    0
MILK               0
MEAT               0
UNIT_PRICE         0
PURCHASE_DATE      0
MAGIC_KEY          0
BOX_COUNT          0
dtype: int64

In [15]:
merged_df.duplicated().sum()

77

In [16]:
df_unique = merged_df.drop_duplicates(keep='last')
df_unique

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,PURCHASE_DATE,MAGIC_KEY,BOX_COUNT
0,1.0,Premium,Home Delivery - CoD,0.0,2.7,9.96,4/2/2019,2C88D36D1FC,1.0
1,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2BF011BDB38,1.0
2,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2CA0EE8F2B3,1.0
3,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2C623730B09,1.0
4,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2/1/2019,2CA6CE1054F,1.0
...,...,...,...,...,...,...,...,...,...
2455859,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,9/10/2018,2BE34886311,1.0
2455860,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,18/10/2018,2BE266F8C55,1.0
2455861,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,18/10/2018,2BDC3619EAF,1.0
2455862,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,17/10/2018,2BF1D98D0B2,1.0
2455863,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,16/10/2018,2C2C8844F09,1.0

In [17]:
df_dropped = df_unique.drop(['PURCHASE_DATE'], axis=1)
df_dropped

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,MAGIC_KEY,BOX_COUNT
0,1.0,Premium,Home Delivery - CoD,0.0,2.7,9.96,2C88D36D1FC,1.0
1,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2BF011BDB38,1.0
2,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2CA0EE8F2B3,1.0
3,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2C623730B09,1.0
4,2.0,Premium,Home Delivery - CoD,0.0,2.3,11.96,2CA6CE1054F,1.0
...,...,...,...,...,...,...,...,...
2455859,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,2BE34886311,1.0
2455860,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,2BE266F8C55,1.0
2455861,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,2BDC3619EAF,1.0
2455862,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,2BF1D98D0B2,1.0
2455863,163.0,Premium,Delivery from Collection Point,0.0,2.2,19.98,2C2C8844F09,1.0

In [18]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df_dropped['QUALITY'] = encoder.fit_transform(df_dropped['QUALITY'])
df_dropped['DELIVERY_OPTION'] = encoder.fit_transform(df_dropped['DELIVERY_OPTION'])
df_dropped

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,MAGIC_KEY,BOX_COUNT
0,1.0,0,1,0.0,2.7,9.96,2C88D36D1FC,1.0
1,2.0,0,1,0.0,2.3,11.96,2BF011BDB38,1.0
2,2.0,0,1,0.0,2.3,11.96,2CA0EE8F2B3,1.0
3,2.0,0,1,0.0,2.3,11.96,2C623730B09,1.0
4,2.0,0,1,0.0,2.3,11.96,2CA6CE1054F,1.0
...,...,...,...,...,...,...,...,...
2455859,163.0,0,0,0.0,2.2,19.98,2BE34886311,1.0
2455860,163.0,0,0,0.0,2.2,19.98,2BE266F8C55,1.0
2455861,163.0,0,0,0.0,2.2,19.98,2BDC3619EAF,1.0
2455862,163.0,0,0,0.0,2.2,19.98,2BF1D98D0B2,1.0
2455863,163.0,0,0,0.0,2.2,19.98,2C2C8844F09,1.0

In [19]:
df_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2455787 entries, 0 to 2455863
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   BOX_ID           float64
 1   QUALITY          int64
 2   DELIVERY_OPTION  int64
 3   MILK             float64
 4   MEAT             float64
 5   UNIT_PRICE       float64
 6   MAGIC_KEY        object
 7   BOX_COUNT        float64
dtypes: float64(5), int64(2), object(1)
memory usage: 168.6+ MB

In [20]:
sub_test_df = df_dropped[df_dropped['MAGIC_KEY'].isin(problem_3_df['MAGIC_KEY'])]
sub_test_df

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,MAGIC_KEY,BOX_COUNT
188,2.0,0,1,0.0,2.3,11.96,2BF645FA065,1.0
423,2.0,0,1,0.0,2.3,11.96,2BE857633DF,1.0
439,2.0,0,1,0.0,2.3,11.96,2BC4EA26F92,1.0
848,2.0,0,1,0.0,2.3,11.96,2BC75E2AC00,1.0
1043,3.0,0,1,0.0,2.4,11.96,2BD8BDFC4E4,1.0
...,...,...,...,...,...,...,...,...
2455795,289.0,1,2,0.0,4.7,15.96,29149CE828C,1.0
2455823,163.0,0,0,0.0,2.2,19.98,290D33249B7,1.0
2455833,163.0,0,0,0.0,2.2,19.98,290D33249B7,1.0
2455835,163.0,0,0,0.0,2.2,19.98,290D33249B7,1.0
2455841,163.0,0,0,0.0,2.2,19.98,290D33249B7,1.0

In [21]:
sub_test_df = sub_test_df.drop_duplicates(subset='MAGIC_KEY', keep='last')
sub_test_df

,BOX_ID,QUALITY,DELIVERY_OPTION,MILK,MEAT,UNIT_PRICE,MAGIC_KEY,BOX_COUNT
188,2.0,0,1,0.0,2.3,11.96,2BF645FA065,1.0
423,2.0,0,1,0.0,2.3,11.96,2BE857633DF,1.0
439,2.0,0,1,0.0,2.3,11.96,2BC4EA26F92,1.0
1043,3.0,0,1,0.0,2.4,11.96,2BD8BDFC4E4,1.0
1119,3.0,0,1,0.0,2.4,11.96,2BFBEB5D2CD,1.0
...,...,...,...,...,...,...,...,...
2454876,276.0,1,0,18.0,2.9,23.98,295CF920444,1.0
2454895,276.0,1,0,18.0,2.9,23.98,2A1008D1F47,1.0
2455294,278.0,1,2,8.5,0.0,10.14,290D83E057F,1.0
2455795,289.0,1,2,0.0,4.7,15.96,29149CE828C,1.0
2455841,163.0,0,0,0.0,2.2,19.98,290D33249B7,1.0

In [22]:
sub_test_df = sub_test_df.reset_index(drop=True)
sample_submission_3 = sample_submission_3.reset_index(drop=True)

sample_submission_3['MAGIC_KEY'] = sub_test_df['MAGIC_KEY']

In [23]:
sample_submission_3

        MAGIC_KEY  MEAT
0     2BF645FA065  25.2
1     2BE857633DF  25.2
2     2BC4EA26F92  25.2
3     2BD8BDFC4E4  25.2
4     2BFBEB5D2CD  25.2
...           ...   ...
5374  295CF920444  25.2
5375  2A1008D1F47  25.2
5376  290D83E057F  25.2
5377  29149CE828C  25.2
5378  290D33249B7  25.2

[5379 rows x 2 columns]

In [24]:
df_dropped.drop(['MAGIC_KEY'], axis=1, inplace=True)
sub_test_df.drop(['MAGIC_KEY'], axis=1, inplace=True)


df_dropped

         BOX_ID  QUALITY  DELIVERY_OPTION  MILK  MEAT  UNIT_PRICE  BOX_COUNT
0           1.0        0                1   0.0   2.7        9.96        1.0
1           2.0        0                1   0.0   2.3       11.96        1.0
2           2.0        0                1   0.0   2.3       11.96        1.0
3           2.0        0                1   0.0   2.3       11.96        1.0
4           2.0        0                1   0.0   2.3       11.96        1.0
...         ...      ...              ...   ...   ...         ...        ...
2455859   163.0        0                0   0.0   2.2       19.98        1.0
2455860   163.0        0                0   0.0   2.2       19.98        1.0
2455861   163.0        0                0   0.0   2.2       19.98        1.0
2455862   163.0        0                0   0.0   2.2       19.98        1.0
2455863   163.0        0                0   0.0   2.2       19.98        1.0

[2455787 rows x 7 columns]

In [25]:
X = df_dropped.drop(['MEAT'], axis=1)
y = df_dropped['MEAT']

sub_test_df = sub_test_df.drop(['MEAT'], axis=1)

X

         BOX_ID  QUALITY  DELIVERY_OPTION  MILK  UNIT_PRICE  BOX_COUNT
0           1.0        0                1   0.0        9.96        1.0
1           2.0        0                1   0.0       11.96        1.0
2           2.0        0                1   0.0       11.96        1.0
3           2.0        0                1   0.0       11.96        1.0
4           2.0        0                1   0.0       11.96        1.0
...         ...      ...              ...   ...         ...        ...
2455859   163.0        0                0   0.0       19.98        1.0
2455860   163.0        0                0   0.0       19.98        1.0
2455861   163.0        0                0   0.0       19.98        1.0
2455862   163.0        0                0   0.0       19.98        1.0
2455863   163.0        0                0   0.0       19.98        1.0

[2455787 rows x 6 columns]

# Normalizations

In [26]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

X = scaler.fit_transform(X)
sub_test_df = scaler.fit_transform(sub_test_df)
X

array([[-1.30275229,  0.        ,  1.        , -0.90909091, -1.33222591,
         0.        ],
       [-1.29357798,  0.        ,  1.        , -0.90909091, -1.        ,
         0.        ],
       [-1.29357798,  0.        ,  1.        , -0.90909091, -1.        ,
         0.        ],
       ...,
       [ 0.18348624,  0.        ,  0.        , -0.90909091,  0.33222591,
         0.        ],
       [ 0.18348624,  0.        ,  0.        , -0.90909091,  0.33222591,
         0.        ],
       [ 0.18348624,  0.        ,  0.        , -0.90909091,  0.33222591,
         0.        ]])

# split datasets

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error

models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'ElasticNet Regression': ElasticNet(),
    'Support Vector Regression': SVR(),
    'Decision Tree Regression': DecisionTreeRegressor(),
    'Random Forest Regression': RandomForestRegressor(),
    'Gradient Boosting Regression': GradientBoostingRegressor(),
    'XGBoost Regression': XGBRegressor(),
    'LightGBM Regression': LGBMRegressor(),
    'CatBoost Regression': CatBoostRegressor()
}

In [29]:
best_model = None
min_mse = float('+inf')
i = 1 # i means number of model
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    if min_mse > mse:
        best_model = model
        min_mse = mse
    print(f'{i}. {model_name} - Mean Squared Error: {mse}')
    i += 1
    if i == 5:
        break

1. Linear Regression - Mean Squared Error: 0.35412913592074585
2. Ridge Regression - Mean Squared Error: 0.354129018469538
3. Lasso Regression - Mean Squared Error: 0.952695592217079
4. ElasticNet Regression - Mean Squared Error: 0.952695592217079

In [30]:
best_model

Ridge()

# Submission

In [31]:
predict = best_model.predict(sub_test_df)
predict

array([2.37588376, 2.37588376, 2.37588376, ..., 0.84046529, 3.02759118,
       3.64927587])

In [32]:
sample_submission_3['MEAT'] = predict

In [33]:
sample_submission_3

        MAGIC_KEY      MEAT
0     2BF645FA065  2.375884
1     2BE857633DF  2.375884
2     2BC4EA26F92  2.375884
3     2BD8BDFC4E4  2.375884
4     2BFBEB5D2CD  2.375884
...           ...       ...
5374  295CF920444  1.595730
5375  2A1008D1F47  1.595730
5376  290D83E057F  0.840465
5377  29149CE828C  3.027591
5378  290D33249B7  3.649276

[5379 rows x 2 columns]

In [34]:
sample_submission_3.to_csv('submission.csv', index=False)